### PR TITLE
Feature/streaming service model

### PR DESCRIPTION
**Pull request by hellovolcano**
In this PR:

- Created the model for the streaming service table
- Created the initial set of CRUD routes for the service table
- Added an unstyled handlebars view to serve up the data for a /services route to display all services

### CODE REVIEW

**Review by Kate-github — COMMENTED** [review]
should we be following some coding standards? Most of the files do not have semicolons at the end of each statement. Also git hub is complaining about new line characters at the end of each file.

**Comment by hellovolcano** [comment]
hi @Kate-github 

1. Semicolons are optional. I think if we want to agree on using them, it's fine, but I think changing my branch via a commit you push up is not standard practice.
2. If/when you have a feedback in a PR, instead of just changing it, you should be leveraging the diff feature to add comments.

**Comment by Kate-github** [comment]
> hi @Kate-github
> 
> 1. Semicolons are optional. I think if we want to agree on using them, it's fine, but I think changing my branch via a commit you push up is not standard practice.
> 2. If/when you have a feedback in a PR, instead of just changing it, you should be leveraging the diff feature to add comments.

Sure will just leave comments from now on. I did use the diff feature, the comment was for all files not just specific to one.

**Comment by hellovolcano** [comment]
Yeah I think your comment is fine, but you also  pushed a commit to my branch...

**Comment by Kate-github** [comment]
> 2\. you should be leveraging the diff feature to add comme

Sorry, I was testing out the edit feature in git hub and it committed the change to your branch. Curiosity got the best of me.

**Review by Kate-github — APPROVED** [review]

**Review by garcia2697 — COMMENTED** [review]
Looks good to me!

**Pull request merged**
