### PR TITLE
Feature/login

### PR DESCRIPTION
**Pull request by Kate-github**
implemented login and signup routes.

### CODE REVIEW

**Review by hellovolcano — APPROVED** [review]
I pulled this down and was able to create a user and then login! Awesome!!

I have a couple pieces of feedback that I don't necessarily think we need to block this PR on, but that we should consider:

- I feel like the logic that you put in the controllers that's capturing the user input might be better moved into a separate .js file in the public/javascript folder, because to me, that fits more with the intent of the "view" concern, which is handling user input. This is how it was modeled in the module content and challenges, as well. I think we can leave it for now, but might want to consider refactoring later if we have time.
- I don't see any api routes for the user; to keep our code clean and organized, it'd be ideal to have a user-routes.js file in the /api folder to handle some basic requests, like the GET requests for the user info (like a GET all and a GET one) that would be nice to have for testing. The login/logout/signup requests look like they're in a good spot to me, though.

Nice work!!

**Comment by Kate-github** [comment]
> I pulled this down and was able to create a user and then login! Awesome!!
> 
> I have a couple pieces of feedback that I don't necessarily think we need to block this PR on, but that we should consider:
> 
> * I feel like the logic that you put in the controllers that's capturing the user input might be better moved into a separate .js file in the public/javascript folder, because to me, that fits more with the intent of the "view" concern, which is handling user input. This is how it was modeled in the module content and challenges, as well. I think we can leave it for now, but might want to consider refactoring later if we have time.
> * I don't see any api routes for the user; to keep our code clean and organized, it'd be ideal to have a user-routes.js file in the /api folder to handle some basic requests, like the GET requests for the user info (like a GET all and a GET one) that would be nice to have for testing. The login/logout/signup requests look like they're in a good spot to me, though.
> 
> Nice work!!

Do we need api routes for the login/signup? The UI is generated using express/handle bars. we only need api routes if we plan on accessing them using fetch.

**Comment by hellovolcano** [comment]
I think it'd be helpful to have GET routes at a minimum for testing. In order to ensure the data looked as expected when I created an account and logged in, I had to use the mysql shell.

**Comment by hellovolcano** [comment]
Actually, looking back at previous guidance... those login/logout routes were actually in a separate user-routes.js file, as well, and the /login route that's defined in home-routes was just to render the page with the passed in data.

Again--it works for now so we can leave it, but something to consider refactoring.

**Pull request merged**
